/**
 * The baked Standard Ebooks catalog: a checked-in snapshot generated by
 * `pnpm update:se-catalog` (scripts/update-se-catalog.mjs), never fetched
 * from a live catalog at runtime. Browsing makes no external requests — the
 * snapshot ships as a hashed same-origin STATIC ASSET (`?url` import keeps
 * only the URL string in the entry bundle) fetched on first panel open. A
 * plain fetch, not a dynamic module import, because a failed module fetch is
 * memoized by the browser's module map and can never be retried without a
 * reload; a fetch is genuinely retryable (per the review-a3-catalog
 * finding). Only adding a book downloads anything else
 * (raw.githubusercontent.com, by repository name).
 *
 * The JSON is first-party build input in the same trust class as source, so
 * this adapter only pins the compile-time shape — the schema/version
 * invariants (exactly 1,000 popularity ranks, unique names, canonical
 * ordering, no unexpected keys) are enforced by the unit test over the real
 * artifact.
 */

import catalogUrl from './standard-ebooks-catalog.json?url';

export type CatalogBook = {
  readonly name: string;
  readonly title: string;
  readonly author: string;
  /** 1-based standardebooks.org popularity rank. */
  readonly popularityRank: number;
};

export type StandardEbooksCatalog = {
  readonly schemaVersion: number;
  readonly generatedAt: string;
  readonly source: { readonly popularityUrl: string };
  readonly books: readonly CatalogBook[];
};

/** Lazily fetch the baked catalog asset. The in-flight promise is memoized at
 *  module scope; a rejection clears it so a retry issues a fresh request. The
 *  parsed JSON is first-party build input in the same trust class as source
 *  (see the module header), so the cast pins shape the same way the old
 *  static import did — the compile-time pin over the real artifact lives in
 *  standard-ebooks-catalog.test.ts, and the schema invariants are enforced
 *  there too. */
let catalogLoad: Promise<StandardEbooksCatalog> | null = null;
export function loadStandardEbooksCatalog(): Promise<StandardEbooksCatalog> {
  if (catalogLoad === null) {
    const load = (async () => {
      const response = await fetch(catalogUrl);
      if (!response.ok) throw new Error(`HTTP ${response.status}`);
      return (await response.json()) as StandardEbooksCatalog;
    })();
    catalogLoad = load;
    load.catch(() => {
      if (catalogLoad === load) catalogLoad = null;
    });
  }
  return catalogLoad;
}
