/**
 * The baked Standard Ebooks catalog: a checked-in snapshot generated by
 * `pnpm update:se-catalog` (scripts/update-se-catalog.mjs), never fetched at
 * runtime. Browsing the catalog costs zero network requests; only adding a
 * book downloads its source (raw.githubusercontent.com, by repository name).
 *
 * The JSON is first-party build input in the same trust class as source, so
 * this adapter only pins the compile-time shape — the schema/version
 * invariants (exactly 100 popularity ranks, unique names, resolvable series
 * members, canonical ordering, no unexpected keys) are enforced by the unit
 * test over the real artifact.
 */

import catalogJson from './standard-ebooks-catalog.json';

export type CatalogBook = {
  readonly name: string;
  readonly title: string;
  readonly author: string;
  /** 1-based standardebooks.org popularity rank; absent for series-only books. */
  readonly popularityRank?: number;
};

export type CatalogSeriesMember = {
  readonly name: string;
  /** Reading-order position within the series (finite, positive). */
  readonly position: number;
};

export type CatalogSeries = {
  readonly slug: string;
  readonly title: string;
  readonly sourceUrl: string;
  readonly members: readonly CatalogSeriesMember[];
};

export type StandardEbooksCatalog = {
  readonly schemaVersion: number;
  readonly generatedAt: string;
  readonly source: { readonly popularityUrl: string };
  readonly books: readonly CatalogBook[];
  readonly series: readonly CatalogSeries[];
};

export const STANDARD_EBOOKS_CATALOG: StandardEbooksCatalog = catalogJson;
